name: Create Shortcut on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  create_shortcut:
    if: github.event.issue.number == 1
    runs-on: macos-latest
    steps:
      - name: Clone repo manually
        run: |
          git clone https://github.com/nickfrey/shortcuts-openapp.git .

      - name: Validate comment content
        id: validate
        run: |
          COMMENT="${{ github.event.comment.body }}"
          COMMENT="${COMMENT//[$'\t\r\n ']/}"
          if [[ ! "$COMMENT" =~ ^[A-Za-z0-9.-]+$ ]]; then
            echo "Invalid app identifier."
            exit 1
          fi
          echo "APP_ID=$COMMENT" >> $GITHUB_ENV

      - name: Prepare shortcut file from template
        run: |
          mkdir -p Shortcuts
          cp shortcut-template.plist Shortcuts/${APP_ID}.shortcut
          sed -i '' "s/\\$APP_ID/${APP_ID}/g" Shortcuts/${APP_ID}.shortcut

      - name: Sign the shortcut file
        run: |
          echo "Memory usage before signing:"
          vm_stat
          top -l 1 -stats mem,cpu
#          /usr/bin/shortcuts sign "Shortcuts/${APP_ID}.shortcut" -o "Shortcuts/${APP_ID}.shortcut"
          for i in {1..3}; do
            echo "Attempt $i to sign shortcut"
            /usr/bin/shortcuts sign "Shortcuts/${APP_ID}.shortcut" -o "Shortcuts/${APP_ID}.shortcut" && break
            echo "Failed attempt $i, retrying..."
            sleep 5
          done
          echo "Memory usage after signing:"
          vm_stat   
          top -l 1 -stats mem,cpu

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Shortcuts/${APP_ID}.shortcut
          git commit -m "Add signed shortcut for ${APP_ID}"
          git push
